
name: CI

on: [push, pull_request]

jobs:
    unit-test:
        runs-on: [php:7.4-cli]

        steps:
            - uses: actions/checkout@v1

            - name: Get composer
              run: |
                  php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
                  php composer-setup.php --install-dir=/usr/bin --filename=composer
                  php -r "unlink('composer-setup.php');"

            - name: Install dependencies
              run: composer install

            - name: PHPUnit tests
              run: ./vendor/bin/phpunit --testdox -c phpunit.xml.dist
