
name: CI

on: [push, pull_request]

jobs:
    unit-test:
        runs-on: [ubuntu-latest]

        steps:
            - uses: actions/checkout@v1

            - name: Install PHP
              run: |
                  sudo apt-get install software-properties-common
                  sudo add-apt-repository ppa:ondrej/php
                  sudo apt-get update
                  sudo apt-get install -y php7.4

            - name: Get composer
              run: |
                  php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
                  sudo php composer-setup.php --install-dir=/usr/bin --filename=composer
                  php -r "unlink('composer-setup.php');"

            - name: Install dependencies
              run: composer install --dev --no-interaction

            - name: phpcs
              run: ./vendor/bin/phpcs

            - name: phpstan
              run: ./vendor/bin/phpstan analyze

            - name: PHPUnit tests
              run: ./vendor/bin/phpunit --testdox -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

            - name: Upload test coverage
              run: ./vendor/bin/php-coveralls
              env:
                  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
